/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Apr 22, 2010, 12:58:44 PM
 */

package chat_client;
import java.io.*;
import java.net.*;

//import java.awt.*;
/**
 *
 * @author Vlad
 */
public class Login extends javax.swing.JFrame {
public static Socket s;
public static DataOutputStream stream;
    /** Creates new form Login */
    public Login(Socket s1) {
        s=Meniu.s;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porecla = new javax.swing.JTextField();
        parola = new javax.swing.JPasswordField();
        reg = new javax.swing.JButton();
        eroare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Porecla");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Parola");

        porecla.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        parola.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parola)
                    .addComponent(porecla, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(porecla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parola, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        reg.setText("Inregistreaza-te");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        eroare.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                eroarePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eroare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reg)
                                .addGap(37, 37, 37)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg)
                    .addComponent(login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(eroare))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String pas=new String(parola.getPassword());
        try {
            stream = new DataOutputStream(s.getOutputStream());
        } catch (IOException ex) {
            System.out.println("Streamul nu poate fi creat");
        }
        try {
            stream.writeUTF("log"+" "+porecla.getText()+" "+pas);
            System.out.println(porecla.getText()+" "+pas);
        } catch (IOException ex) {
            System.out.println("textul nu poate fi scris");
            return;
        }
        if (porecla.getText().equals("/quit"))
        {
            this.dispose();
            Input.ok=false;
            try {
                s.close();
            } catch (IOException ex) {
               System.out.println("Socketul nu poate fi inchis");
               return;
            }
        }
        /*if (eroare.getText().equals("bine"))
        {
            this.dispose();
            Chat_Client.c.setVisible(true);
        }*/
    }//GEN-LAST:event_loginActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            stream = new DataOutputStream(s.getOutputStream());
        } catch (IOException ex) {
            System.out.println("Streamul nu poate fi creat");
        }
        try {
            stream.writeUTF("/quit");
        } catch (IOException ex) {
            System.out.println("textul nu poate fi scris");
        }
        Input.ok=false;
            try {
                s.close();
            } catch (IOException ex) {
               System.out.println("Socketul nu poate fi inchis");
            }
    
    }//GEN-LAST:event_formWindowClosing

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        String pas=new String(parola.getPassword());
        try {
            stream = new DataOutputStream(s.getOutputStream());
        } catch (IOException ex) {
            System.out.println("Streamul nu poate fi creat");
        }
        try {
            stream.writeUTF("reg"+" "+porecla.getText()+" "+pas);
            System.out.println(porecla.getText()+" "+pas);
        } catch (IOException ex) {
            System.out.println("textul nu poate fi scris");
            return;
        }
        if (porecla.getText().equals("/quit"))
        {
            this.dispose();
            Input.ok=false;
            try {
                s.close();
            } catch (IOException ex) {
               System.out.println("Socketul nu poate fi inchis");
               return;
            }
        }
        /*if (eroare.getText().equals("bine"))
        {
            this.dispose();
            Chat_Client.c.setVisible(true);
        }*/
    }//GEN-LAST:event_regActionPerformed

    private void eroarePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_eroarePropertyChange
        if (eroare.getText().equals("bine"))
        {
            Meniu.m.setVisible(true);
            eroare.removePropertyChangeListener(eroare.getPropertyChangeListeners()[0]);
            this.dispose();
        }
    }//GEN-LAST:event_eroarePropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(s).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel eroare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField parola;
    private javax.swing.JTextField porecla;
    private javax.swing.JButton reg;
    // End of variables declaration//GEN-END:variables

}
