/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Meniu.java
 *
 * Created on May 9, 2010, 1:06:53 AM
 */

package chat_client;
import java.awt.Color;
import java.awt.Component;
import java.io.*;
import java.net.*;
import javax.swing.*;
/**
 *
 * @author Vlad
 */
class LabelListCellRenderer extends DefaultListCellRenderer {

    public LabelListCellRenderer(){
        super();
    }

    @Override
    public Component getListCellRendererComponent(JList list, Object value,
            int index, boolean isSelected, boolean hasFocus) {
        JLabel j=new JLabel();
        if(JLabel.class.isInstance(value))
        {
            j= (JLabel)value;
            if (isSelected) {j.setBackground(Color.BLACK);j.setForeground(Color.blue);}
            else {j.setBackground(Color.white);j.setForeground(Color.black);}
            return j;
        }
        return super.getListCellRendererComponent(list, value,
                index, isSelected, hasFocus);
    }

}

public class Meniu extends javax.swing.JFrame {
public static Socket s;
public static Meniu m;
public static int n;
public static DefaultListModel model;
public static DataOutputStream stream;
public static Chat_Client c[]=new Chat_Client[30];
public static Conferinta conf ;
public static ImageIcon icon = new ImageIcon("1.gif");
public static ImageIcon icon2 = new ImageIcon("2.gif");
    /** Creates new form Meniu */
    public Meniu() {
        initComponents();
        model = new DefaultListModel();
        Lista.setCellRenderer(new LabelListCellRenderer());
        Lista.setModel(model);
        n=0;
    }
    public void adauga(String s1,String s2)
    {
        JLabel j=new JLabel();
        j.setText(s1);
        if (s2.equals("*")) j.setIcon(icon2);
        else j.setIcon(icon);
         model.addElement(j);
         n++;
    }
    public void stare(Boolean a,String s1)
    {
        JLabel j=new JLabel();
        j.setText(s1);
        for (int i=0;i<n;i++)
            if (s1.equals(((JLabel)model.getElementAt(i)).getText()))
            {
                System.out.println((((JLabel)model.getElementAt(i)).getText()));
                if (a) j.setIcon(icon);
                else j.setIcon(icon2);
                model.set(i, j);
                break;
            }
    }
    public int pozitie(String s1)
    {
        for (int i=0;i<n;i++)
            if (s1.equals(((JLabel)model.getElementAt(i)).getText()))
                return i;
        return -1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList();
        adauga = new javax.swing.JButton();
        prieten_nou = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        actiuni = new javax.swing.JMenu();
        inv_conf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista);

        adauga.setText("+");
        adauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugaActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        actiuni.setText("Actiuni");

        inv_conf.setText("Invita la conferinta");
        inv_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_confActionPerformed(evt);
            }
        });
        actiuni.add(inv_conf);

        jMenuBar1.add(actiuni);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adauga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prieten_nou, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adauga)
                    .addComponent(prieten_nou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseClicked
        if (evt.getClickCount() == 2) {
            int index = Lista.locationToIndex(evt.getPoint());
            System.out.println("Double clicked on Item " + index);
            JLabel j=new JLabel();
            j=(JLabel)model.getElementAt(index);
            if (c[index] == null)
            {
                c[index] =new Chat_Client(j.getText());
                c[index].setVisible(true);
                System.out.println(c[index].getTitle());
            }
         }

    }//GEN-LAST:event_ListaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            stream = new DataOutputStream(s.getOutputStream());
        } catch (IOException ex) {
            System.out.println("Streamul nu poate fi creat");
        }
        try {
            stream.writeUTF("/quit");
        } catch (IOException ex) {
            System.out.println("textul nu poate fi scris");
        }
        Input.ok=false;
            try {
                s.close();
            } catch (IOException ex) {
               System.out.println("Socketul nu poate fi inchis");
            }
    }//GEN-LAST:event_formWindowClosing

    private void adaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugaActionPerformed
        boolean error;
        error=false;
        for (int i=0;i<n;i++)
            if (prieten_nou.getText().equals(((JLabel)model.getElementAt(i)).getText()))
            {
                error=true;
            }
        if (error) JOptionPane.showMessageDialog(Meniu.m,"Aceasta porecla exista deja in lista","Eroare",JOptionPane.ERROR_MESSAGE);
        else
        {
            try {
                stream = new DataOutputStream(s.getOutputStream());
            } catch (IOException ex) {
                System.out.println("Streamul nu poate fi creat");
            }
            try {
                stream.writeUTF("/cauta "+prieten_nou.getText());
            } catch (IOException ex) {
                System.out.println("textul nu poate fi scris");
                return;
            }
        }
        prieten_nou.setText("");
    }//GEN-LAST:event_adaugaActionPerformed

    private void inv_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_confActionPerformed
        Conf_setup invitatie=new Conf_setup();
        invitatie.setVisible(true);
    }//GEN-LAST:event_inv_confActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                m=new Meniu();
                //m.setVisible(true);
                try {
                       s = new Socket("localhost", 1234);
                    }
                catch (IOException e) {
                    System.out.println("Nu ma pot conecta la server.");
                    m.dispose();
                    }
                Login l=new Login(s);
                l.setVisible(true);
                //c.setVisible(true);
        System.out.println("Porecla:");



        try {
            new Input(s);
        }
        catch (IOException e) {
            System.out.println("Eroare la input.");
            m.dispose();
        }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Lista;
    private javax.swing.JMenu actiuni;
    private javax.swing.JButton adauga;
    private javax.swing.JMenuItem inv_conf;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prieten_nou;
    // End of variables declaration//GEN-END:variables

}
